/* Generated by Nim Compiler v0.12.0 */
/*   (c) 2015 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   gcc -c  -w  -I/usr/lib/nim -o /home/lee/nim_projects/deep_reversi/nimcache/test.o /home/lee/nim_projects/deep_reversi/nimcache/test.c */
#define NIM_INTBITS 64

#include "nimbase.h"
#include <stdio.h>
typedef struct StudentHEX3Aobjecttype95011 StudentHEX3Aobjecttype95011;
typedef struct PersonHEX3Aobjecttype95007 PersonHEX3Aobjecttype95007;
typedef struct TNimObject TNimObject;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef struct Cell49347 Cell49347;
typedef struct Cellseq49363 Cellseq49363;
typedef struct Gcheap51418 Gcheap51418;
typedef struct Gcstack51416 Gcstack51416;
typedef struct Cellset49359 Cellset49359;
typedef struct Pagedesc49355 Pagedesc49355;
typedef struct Memregion31291 Memregion31291;
typedef struct Smallchunk31243 Smallchunk31243;
typedef struct Llchunk31285 Llchunk31285;
typedef struct Bigchunk31245 Bigchunk31245;
typedef struct Intset31217 Intset31217;
typedef struct Trunk31213 Trunk31213;
typedef struct Avlnode31289 Avlnode31289;
typedef struct Gcstat51414 Gcstat51414;
typedef struct Basechunk31241 Basechunk31241;
typedef struct Freecell31233 Freecell31233;
typedef N_NIMCALL_PTR(void, TY3889) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, TY3894) (void* p);
struct  TNimType  {
NI size;
NU8 kind;
NU8 flags;
TNimType* base;
TNimNode* node;
void* finalizer;
TY3889 marker;
TY3894 deepcopy;
};
struct  TNimObject  {
TNimType* m_type;
};
struct  TGenericSeq  {
NI len;
NI reserved;
};
struct  NimStringDesc  {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
struct  PersonHEX3Aobjecttype95007  {
  TNimObject Sup;
NimStringDesc* name;
NI age;
};
struct  StudentHEX3Aobjecttype95011  {
  PersonHEX3Aobjecttype95007 Sup;
NI id;
};
struct  TNimNode  {
NU8 kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
struct  Cell49347  {
NI refcount;
TNimType* typ;
};
struct  Cellseq49363  {
NI len;
NI cap;
Cell49347** d;
};
struct  Cellset49359  {
NI counter;
NI max;
Pagedesc49355* head;
Pagedesc49355** data;
};
typedef Smallchunk31243* TY31306[512];
typedef Trunk31213* Trunkbuckets31215[256];
struct  Intset31217  {
Trunkbuckets31215 data;
};
struct  Memregion31291  {
NI minlargeobj;
NI maxlargeobj;
TY31306 freesmallchunks;
Llchunk31285* llmem;
NI currmem;
NI maxmem;
NI freemem;
NI lastsize;
Bigchunk31245* freechunkslist;
Intset31217 chunkstarts;
Avlnode31289* root;
Avlnode31289* deleted;
Avlnode31289* last;
Avlnode31289* freeavlnodes;
};
struct  Gcstat51414  {
NI stackscans;
NI cyclecollections;
NI maxthreshold;
NI maxstacksize;
NI maxstackcells;
NI cycletablesize;
NI64 maxpause;
};
struct  Gcheap51418  {
Gcstack51416* stack;
void* stackbottom;
NI cyclethreshold;
Cellseq49363 zct;
Cellseq49363 decstack;
Cellset49359 cycleroots;
Cellseq49363 tempstack;
NI recgclock;
Memregion31291 region;
Gcstat51414 stat;
};
struct  Gcstack51416  {
Gcstack51416* prev;
Gcstack51416* next;
void* starts;
void* pos;
NI maxstacksize;
};
typedef NI TY31222[8];
struct  Pagedesc49355  {
Pagedesc49355* next;
NI key;
TY31222 bits;
};
struct  Basechunk31241  {
NI prevsize;
NI size;
NIM_BOOL used;
};
struct  Smallchunk31243  {
  Basechunk31241 Sup;
Smallchunk31243* next;
Smallchunk31243* prev;
Freecell31233* freelist;
NI free;
NI acc;
NF data;
};
struct  Llchunk31285  {
NI size;
NI acc;
Llchunk31285* next;
};
struct  Bigchunk31245  {
  Basechunk31241 Sup;
Bigchunk31245* next;
Bigchunk31245* prev;
NI align;
NF data;
};
struct  Trunk31213  {
Trunk31213* next;
NI key;
TY31222 bits;
};
typedef Avlnode31289* TY31296[2];
struct  Avlnode31289  {
TY31296 link;
NI key;
NI upperbound;
NI level;
};
struct  Freecell31233  {
Freecell31233* next;
NI zerofield;
};
N_NIMCALL(void, nimGCvisit)(void* d, NI op);
N_NIMCALL(void, TMP141)(void* p, NI op);
N_NIMCALL(void*, newObj)(TNimType* typ, NI size);
N_NIMCALL(NimStringDesc*, copyStringRC1)(NimStringDesc* src);
static N_INLINE(void, nimGCunrefNoCycle)(void* p);
static N_INLINE(Cell49347*, usrtocell_53046)(void* usr);
static N_INLINE(void, nimFrame)(TFrame* s);
N_NOINLINE(void, stackoverflow_23601)(void);
static N_INLINE(void, popFrame)(void);
static N_INLINE(void, rtladdzct_54604)(Cell49347* c);
N_NOINLINE(void, addzct_53017)(Cellseq49363* s, Cell49347* c);
static N_INLINE(void, asgnRef)(void** dest, void* src);
static N_INLINE(void, incref_55422)(Cell49347* c);
static N_INLINE(NIM_BOOL, canbecycleroot_53067)(Cell49347* c);
static N_INLINE(void, rtladdcycleroot_53823)(Cell49347* c);
N_NOINLINE(void, incl_50065)(Cellset49359* s, Cell49347* cell);
static N_INLINE(void, decref_55004)(Cell49347* c);
N_NIMCALL(void, TMP143)(void* p, NI op);
N_NIMCALL(NimStringDesc*, HEX24_95040)(StudentHEX3Aobjecttype95011* x);
N_NIMCALL(NimStringDesc*, HEX24_95610)(PersonHEX3Aobjecttype95007* x);
static N_INLINE(void, initStackBottomWith)(void* locals);
N_NOINLINE(void, setStackBottom)(void* thestackbottom);
NIM_EXTERNC N_NOINLINE(void, systemInit000)(void);
NIM_EXTERNC N_NOINLINE(void, systemDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, testInit000)(void);
NIM_EXTERNC N_NOINLINE(void, testDatInit000)(void);
STRING_LITERAL(TMP142, "Anton", 5);
STRING_LITERAL(TMP144, "Jude", 4);
STRING_LITERAL(TMP145, "John", 4);
StudentHEX3Aobjecttype95011* student_95017;
PersonHEX3Aobjecttype95007* person_95018;
extern TNimType NTI4011; /* RootObj */
TNimType NTI95007; /* Person:ObjectType */
extern TNimType NTI149; /* string */
extern TNimType NTI108; /* int */
TNimType NTI95011; /* Student:ObjectType */
TNimType NTI95006; /* Student */
extern TFrame* frameptr_20842;
extern Gcheap51418 gch_51459;
TNimType NTI95004; /* Person */
NIM_CHAR x_96009;
N_NIMCALL(void, TMP141)(void* p, NI op) {
	StudentHEX3Aobjecttype95011* a;
	a = (StudentHEX3Aobjecttype95011*)p;
	nimGCvisit((void*)(*a).Sup.name, op);
}

static N_INLINE(void, nimFrame)(TFrame* s) {
	NI LOC1;
	LOC1 = 0;
	{
		if (!(frameptr_20842 == NIM_NIL)) goto LA4;
		LOC1 = ((NI) 0);
	}
	goto LA2;
	LA4: ;
	{
		LOC1 = ((NI) ((NI16)((*frameptr_20842).calldepth + ((NI16) 1))));
	}
	LA2: ;
	(*s).calldepth = ((NI16) (LOC1));
	(*s).prev = frameptr_20842;
	frameptr_20842 = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA9;
		stackoverflow_23601();
	}
	LA9: ;
}

static N_INLINE(void, popFrame)(void) {
	frameptr_20842 = (*frameptr_20842).prev;
}

static N_INLINE(Cell49347*, usrtocell_53046)(void* usr) {
	Cell49347* result;
	nimfr("usrToCell", "gc.nim")
	result = 0;
	nimln(131, "gc.nim");
	result = ((Cell49347*) ((NI)((NU64)(((NI) (usr))) - (NU64)(((NI)sizeof(Cell49347))))));
	popFrame();
	return result;
}

static N_INLINE(void, rtladdzct_54604)(Cell49347* c) {
	nimfr("rtlAddZCT", "gc.nim")
	nimln(212, "gc.nim");
	addzct_53017((&gch_51459.zct), c);
	popFrame();
}

static N_INLINE(void, nimGCunrefNoCycle)(void* p) {
	Cell49347* c;
	nimfr("nimGCunrefNoCycle", "gc.nim")
	nimln(246, "gc.nim");
	c = usrtocell_53046(p);
	nimln(248, "gc.nim");
	{
		nimln(180, "gc.nim");
		(*c).refcount -= ((NI) 8);
		nimln(181, "gc.nim");
		if (!((NU64)((*c).refcount) < (NU64)(((NI) 8)))) goto LA3;
		nimln(249, "gc.nim");
		rtladdzct_54604(c);
	}
	LA3: ;
	popFrame();
}

static N_INLINE(NIM_BOOL, canbecycleroot_53067)(Cell49347* c) {
	NIM_BOOL result;
	nimfr("canBeCycleRoot", "gc.nim")
	result = 0;
	nimln(134, "gc.nim");
	nimln(1104, "system.nim");
	result = !((((*(*c).typ).flags &(1<<((((NU8) 1))&7)))!=0));
	popFrame();
	return result;
}

static N_INLINE(void, rtladdcycleroot_53823)(Cell49347* c) {
	nimfr("rtlAddCycleRoot", "gc.nim")
	nimln(202, "gc.nim");
	{
		nimln(349, "system.nim");
		nimln(147, "gc.nim");
		if (!!((((NI) ((NI)((*c).refcount & ((NI) 3)))) == ((NI) 3)))) goto LA3;
		nimln(152, "gc.nim");
		(*c).refcount = (NI)((NI)((*c).refcount & ((NI) -4)) | ((NI) 3));
		nimln(204, "gc.nim");
		incl_50065((&gch_51459.cycleroots), c);
	}
	LA3: ;
	popFrame();
}

static N_INLINE(void, incref_55422)(Cell49347* c) {
	nimfr("incRef", "gc.nim")
	nimln(229, "gc.nim");
	(*c).refcount = (NI)((NU64)((*c).refcount) + (NU64)(((NI) 8)));
	nimln(232, "gc.nim");
	{
		NIM_BOOL LOC3;
		LOC3 = 0;
		LOC3 = canbecycleroot_53067(c);
		if (!LOC3) goto LA4;
		nimln(233, "gc.nim");
		rtladdcycleroot_53823(c);
	}
	LA4: ;
	popFrame();
}

static N_INLINE(void, decref_55004)(Cell49347* c) {
	nimfr("decRef", "gc.nim")
	nimln(219, "gc.nim");
	{
		nimln(180, "gc.nim");
		(*c).refcount -= ((NI) 8);
		nimln(181, "gc.nim");
		if (!((NU64)((*c).refcount) < (NU64)(((NI) 8)))) goto LA3;
		nimln(220, "gc.nim");
		rtladdzct_54604(c);
	}
	goto LA1;
	LA3: ;
	{
		NIM_BOOL LOC6;
		nimln(221, "gc.nim");
		LOC6 = 0;
		LOC6 = canbecycleroot_53067(c);
		if (!LOC6) goto LA7;
		nimln(224, "gc.nim");
		rtladdcycleroot_53823(c);
	}
	goto LA1;
	LA7: ;
	LA1: ;
	popFrame();
}

static N_INLINE(void, asgnRef)(void** dest, void* src) {
	nimfr("asgnRef", "gc.nim")
	nimln(257, "gc.nim");
	{
		Cell49347* LOC5;
		nimln(349, "system.nim");
		if (!!((src == NIM_NIL))) goto LA3;
		nimln(257, "gc.nim");
		LOC5 = 0;
		LOC5 = usrtocell_53046(src);
		incref_55422(LOC5);
	}
	LA3: ;
	nimln(258, "gc.nim");
	{
		Cell49347* LOC10;
		nimln(349, "system.nim");
		if (!!(((*dest) == NIM_NIL))) goto LA8;
		nimln(258, "gc.nim");
		LOC10 = 0;
		LOC10 = usrtocell_53046((*dest));
		decref_55004(LOC10);
	}
	LA8: ;
	nimln(259, "gc.nim");
	(*dest) = src;
	popFrame();
}
N_NIMCALL(void, TMP143)(void* p, NI op) {
	PersonHEX3Aobjecttype95007* a;
	a = (PersonHEX3Aobjecttype95007*)p;
	nimGCvisit((void*)(*a).name, op);
}

static N_INLINE(void, initStackBottomWith)(void* locals) {
	setStackBottom(locals);
}
void PreMainInner() {
	systemInit000();
	testDatInit000();
}

void PreMain() {
	void (*volatile inner)();
	systemDatInit000();
	inner = PreMainInner;
	initStackBottomWith((void *)&inner);
	(*inner)();
}

int cmdCount;
char** cmdLine;
char** gEnv;
N_CDECL(void, NimMainInner)(void) {
	testInit000();
}

N_CDECL(void, NimMain)(void) {
	void (*volatile inner)();
	PreMain();
	inner = NimMainInner;
	initStackBottomWith((void *)&inner);
	(*inner)();
}

int main(int argc, char** args, char** env) {
	cmdLine = args;
	cmdCount = argc;
	gEnv = env;
	NimMain();
	return nim_program_result;
}

NIM_EXTERNC N_NOINLINE(void, testInit000)(void) {
	StudentHEX3Aobjecttype95011* LOC1;
	NimStringDesc* LOC2;
	PersonHEX3Aobjecttype95007* LOC3;
	NimStringDesc* LOC4;
	NimStringDesc* LOC5;
	NimStringDesc* LOC6;
	NimStringDesc* LOC7;
	nimfr("test", "test.nim")
	nimln(13, "test.nim");
	LOC1 = 0;
	LOC1 = (StudentHEX3Aobjecttype95011*) newObj((&NTI95006), sizeof(StudentHEX3Aobjecttype95011));
	(*LOC1).Sup.Sup.m_type = (&NTI95011);
	LOC2 = 0;
	LOC2 = (*LOC1).Sup.name; (*LOC1).Sup.name = copyStringRC1(((NimStringDesc*) &TMP142));
	if (LOC2) nimGCunrefNoCycle(LOC2);
	(*LOC1).Sup.age = ((NI) 5);
	(*LOC1).id = ((NI) 2);
	asgnRef((void**) (&student_95017), LOC1);
	nimln(14, "test.nim");
	LOC3 = 0;
	LOC3 = (PersonHEX3Aobjecttype95007*) newObj((&NTI95004), sizeof(PersonHEX3Aobjecttype95007));
	(*LOC3).Sup.m_type = (&NTI95007);
	LOC4 = 0;
	LOC4 = (*LOC3).name; (*LOC3).name = copyStringRC1(((NimStringDesc*) &TMP144));
	if (LOC4) nimGCunrefNoCycle(LOC4);
	(*LOC3).age = ((NI) 20);
	asgnRef((void**) (&person_95018), LOC3);
	nimln(15, "test.nim");
	(*student_95017).id = ((NI) 6);
	nimln(16, "test.nim");
	LOC5 = 0;
	LOC5 = (*student_95017).Sup.name; (*student_95017).Sup.name = copyStringRC1(((NimStringDesc*) &TMP145));
	if (LOC5) nimGCunrefNoCycle(LOC5);
	nimln(17, "test.nim");
	LOC6 = 0;
	LOC6 = HEX24_95040((&(*student_95017)));
	printf("%s\012", LOC6? (LOC6)->data:"nil");
	nimln(18, "test.nim");
	LOC7 = 0;
	LOC7 = HEX24_95610((&(*person_95018)));
	printf("%s\012", LOC7? (LOC7)->data:"nil");
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, testDatInit000)(void) {
static TNimNode* TMP140[2];
static TNimNode TMP138[4];
NTI95007.size = sizeof(PersonHEX3Aobjecttype95007);
NTI95007.kind = 17;
NTI95007.base = (&NTI4011);
TMP140[0] = &TMP138[1];
TMP138[1].kind = 1;
TMP138[1].offset = offsetof(PersonHEX3Aobjecttype95007, name);
TMP138[1].typ = (&NTI149);
TMP138[1].name = "name";
TMP140[1] = &TMP138[2];
TMP138[2].kind = 1;
TMP138[2].offset = offsetof(PersonHEX3Aobjecttype95007, age);
TMP138[2].typ = (&NTI108);
TMP138[2].name = "age";
TMP138[0].len = 2; TMP138[0].kind = 2; TMP138[0].sons = &TMP140[0];
NTI95007.node = &TMP138[0];
NTI95011.size = sizeof(StudentHEX3Aobjecttype95011);
NTI95011.kind = 17;
NTI95011.base = (&NTI95007);
TMP138[3].kind = 1;
TMP138[3].offset = offsetof(StudentHEX3Aobjecttype95011, id);
TMP138[3].typ = (&NTI108);
TMP138[3].name = "id";
NTI95011.node = &TMP138[3];
NTI95006.size = sizeof(StudentHEX3Aobjecttype95011*);
NTI95006.kind = 22;
NTI95006.base = (&NTI95011);
NTI95006.marker = TMP141;
NTI95004.size = sizeof(PersonHEX3Aobjecttype95007*);
NTI95004.kind = 22;
NTI95004.base = (&NTI95007);
NTI95004.marker = TMP143;
}

